import { Poppins } from "next/font/google";
import './globals.css';
import { Metadata } from 'next';

// Correct usage of Poppins with font weight and style
const poppins = Poppins({
  weight: ['400', '700'], // Specify the font weights you need
  subsets: ['latin'], // Subset should be passed here, not in style
  style: ['normal', 'italic'], // Optional: If you need both normal and italic styles
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
